### ISSUE TITLE
Plotting defaults: for more uniform appearance (especially font size)

### ISSUE THREAD

**Issue by eleanorfrajka** [callumrollo/glidertest#107]
Is there a useful way to set some plotting defaults globally?

I have in mind that the plots created could all be designed to be best viewed as either a half-width powerpoint figure or a full-width, so that in the end, it would be useful to have a default figsize (fullwidth,height) or figsize(halfwidth, height).  Height could be variable or a set of standard values that then correspond to (for a paper) whether they are fullheight, halfheight, thirdheight, fourthheight, etc for whether the figure is intended to be the height of a whole page, half the height of a page, a third the height, etc.

This is because when we then also set a default font size everywhere, the size of the figure generated affects how the font size appears.  font size 14 is nice, unless you have a giant figure that is A3-sized or something.

At the moment, 
- plot_updown_bias defaults to figsize (5,5), 
- plot_basic_vars to (15,5)
- process_optics_assess might not have any default
- plot_daynight_avg is (5,5)
- plot_quench_assess (5,5)
- check_temporal_drift (14,6)
- plot_prof_monotony (10,5)
- plot_glider_track (10,6)
- plot_grid_spacing (14,6)
- plot_ts (14, 4.5)
- plot_vertical_speeds_with_histograms is (14,12)
- plot_combined_velocity_profiles is (4.8,4.8)

It appears to have units of inches: https://www.geeksforgeeks.org/how-to-change-the-size-of-figures-drawn-with-matplotlib/
And it appears to be the size of the figure including axes and labels and annotations (so not the axes sizes).

Preferred behaviour would be for the figures generated by glidertest to look mostly OK (i.e., font sizes are legible) when the figure is dropped somewhere else like a printed document or a powerpoint slide.  Ideally, they would also look somewhat uniform.

Documents:

- US letter paper is 8.5 x 11", for margins of 1 inch, then text width is 6.5" x 9"
- A4 paper  8.3 x 11.7", margins typically 2.5cm (1 inch) so that text width is 6.3" and height is 9.7"

Powerpoint default document in widescreen is

- 33.87 cm x 19.05 cm = 13.3" x 7.5", but the effective size is smaller since usually a large fraction of the slide area is devoted to the title, so the effective height is maybe 5" and the width is 11.4"

By my non-scientific tests of using the figsize (14,6) and font size 14, and then dropping the figure into word, the effective font size became about 8.  I think a minimum of effective 9 should be aimed for, which would be a default font size of 15 for a figure width of 14.

Then for half-width as in a two-column paper where the figure is in one column only (say, figsize (6.75, HH), slightly smaller to account for some width of the column) the same default font size of 15 should end up with approximately a font size of 9.  

This combination gives about a font size of 16 in powerpoint, which seems acceptable.

Using a set of defaults when fig is not passed to the plotting function makes sense to me.  Behaviour will be different when fig/ax is passed, in which case it might be useful to allow the user (or other wrapper functions) to also pass a default font size which is then possibly aware of the figure width??

One possible approach: Update all `plots.py` functions to use a width of either **14** or **6.75** (and adjust the vertical accordingly), and to use a `def_font_size` of **15** (and accept this as an optional input).  Or is there a better way?  a set of parameters that can be set in one place (`utilities.py`) and then called?

**Comment by MOchiara** [comment]
I think we can define a glidertest style and then let the user modify that if needed to adapt to whatever else they want
