### ISSUE TITLE
feature: Oxygen test

### ISSUE THREAD

**Issue by eleanorfrajka** [callumrollo/glidertest#109]
I use profiles of oxygen saturation as a quick check of oxygen data quality.  Can be calculated using Gibbs Seawater functions.

My expectation is that the real ocean, near the surface, is near saturation in the surface mixed layer (especially when there's active mixing).  If it's not, then I'll mistrust the oxygen data.

Exceptions could be when there's an active bloom or lots of waves (and hence bubbles), and then you could have super saturation.

So, maybe a calculation of oxygen saturation and a profile of oxygen saturation over some width of dives.  And maybe a time series of oxygen saturation averaged either in the mixed layer or over the top 20m (or mixed layer, whichever is saturated)?

Actually, a brief check of oxygen SOP (https://oceangliderscommunity.github.io/Oxygen_SOP/sections/oxygen_dmqc.html):
- Looks like day/night averages (and "noise" near the surface during daylight vs, presumably absence in noise at nighttime) could indicate foil damage.

Maybe think about implementing some of these? 
https://oceangliderscommunity.github.io/Oxygen_SOP/sections/oxygen_rtqc.html

- [ ] 6.2.2 Global range check could be illustrated with a histogram
- [ ] 6.2.3 Outlier and spike check could be implemented to find out how many spikes there are in the dataset overall (within a phase, calculate this 'test value' quantity, and check for thresholds as supplied, then make a histogram of "test_value" for phase ascent and for phase descent?
- [ ] 6.2.4 Check for identical values, illustrated with a histogram of diff(DOXY) for phase ascent and for phase descent
- [ ] 6.2.6 Effects of biofouling.  Well, I don't think we could do this so well, but maybe check_temporal_drift could have additional behaviour to either check drift within a specified depth range (plim=[20,30]) or.. within the surface mixed layer?  As it currently is in the demo, it's hard to look for drift when doxy runs from 0 to 350.

![image](https://github.com/user-attachments/assets/704f185d-7913-41d3-918f-61f3c605d9f1)

**Comment by MOchiara** [comment]
Yeah maybe it is hard to see the drift but for VOTO when we had big issues you would easily notice it regardless hahah
I am working on some functions to implement those checks now
![image](https://github.com/user-attachments/assets/bc4f24db-8341-4142-acce-ea3909be4caf)
