### ISSUE TITLE
Reorder demo notebook

### ISSUE THREAD

**Issue by eleanorfrajka** [callumrollo/glidertest#127]
The demo notebook is currently in somewhat random order.  I suggest an ordering of:

## Vertical velocity

So major headers are ##, including overview, then each instrument, roughly ordered by my subjective view for what people are likely to have installed (bio-optics and oxygen could be in either order) or available in their OG1 dataset (so vertical velocity currently at the end - also because it uses a different sample dataset).

I've reordered it in my branch, but it seems like it'll generate a lot of merge conflicts if anyone is working on this at the moment.

**Comment by callumrollo** [comment]
I'm not working on any notebook stuff atm, go ahead and put in a PR :)
