### ISSUE TITLE
Package issue "ImportError: cannot import name 'omm' from 'sgp4' "

### ISSUE THREAD

**Issue by eleanorfrajka** [callumrollo/glidertest#34]
I'm running into a problem when importing the tools from glidertest.  

It looks like the skyfield package requires the sgp4 package (for which I have version 2.10).  The latest version is 2.23, and the 'omm' function/package only came about sometime after 2020 (looks like version 2.14 - https://pypi.org/project/sgp4/).  I re-installed the environment, forcing version 2.23 and now it works.  Can we include this in the requirements file somehow?

**Comment by callumrollo** [comment]
Thanks for the catch and thorough explanation! I was able to reproduce this and confirm that  sgp4>=2.14 fixes it.

I've added sgp4>=2.14 to the requirements to fix this going forward. #35 

It's odd that sgp 2.10 causes an error, as skyfield itself only requires >2.2, hence why installing the current requirements allowed sgp4 version 2.10 https://github.com/skyfielders/python-skyfield/blob/2d104a43b47ad37e783038ed96fb8048132fb778/setup.py#L60

Looks like an error in the requirements of the skyfield package
