### ISSUE TITLE
Add optics variables in the example files

### ISSUE THREAD

**Issue by MOchiara** [callumrollo/glidertest#4]
It would be nice to have all optics varibales in the example files so we can write code to check for quenching, drift etc
@callumrollo

**Comment by eleanorfrajka** [comment]
Where is the example file?  

I thought we'd be able to use the one from OG, but those are tiny little snippets.  Not even a full dive.  I also started converting a VOTO dataset to OG1, but got stuck - are the engineering variables named in OG1/or a reference vocabulary?

**Comment by callumrollo** [comment]
No worries! The nice thing about the example datasets being separate is we only need to change a couple of lines in `fetchers.py` to update to a new one.

I've started by adding a full delayed mode mission in #5

 I'll work on this more tomorrow to add the variables Chiara requested

**Comment by callumrollo** [comment]
We now have two example files, one of which has PAR. @MOchiara does that cover all the variables we need for now? If so we can close this issue

**Comment by MOchiara** [comment]
Yeah I think we can close this issue as we have all we need for now
