### ISSUE TITLE
tests!

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/glidertest#77]
Every function should have a test. Even if it's just running the function. Cool additions to have:

- testable output (like a number or True/False it is expected to return)
- test expected failure (e.g. if a key variable is not present)
- test plots? Not sure how to do this, but have seen it done in gliderpy https://github.com/ioos/gliderpy/blob/main/tests/test_plotting.py

**Comment by MOchiara** [comment]
Issues closed for now with #86
